---
version: '3'
services:
  packer:
    build:
      context: ./packer
    dns_search: home.local
    dns:
      - 192.168.200.1
    volumes:
      - ./workspace:/packer
      - ./ssh:/keys
    entrypoint: bash /packer/start.sh
